deployments:
  odoo:
    pre_launch:
      - target: db
        command: exec
        options: "{target} bash -c 'ls -la ./'"
    post_launch:
      - target: db1
        command: exec
        options: "{target} bash -c 'echo test && echo test > test'"
      - target: web
        command: exec
        options: "{target} bash -c 'ls -la ./'"
