deployments:
  odoo:
    dockerimage: odoo:10.0
    dockerfileonly: true
    port_forwarding: 80:8069
    run_options: -e HOST=$(echo $POSTGRESQL | cut -f1 -d":")
    depends_on:
      - POSTGRESQL:
          app: odoo-test:postgres
  postgres:
    dockerimage: postgres:9.4
    run_options: -e POSTGRES_PASSWORD=odoo -e POSTGRES_USER=odoo
    check_service_ports: 5432
    port_forwarding: 5432:5432
