deployments:
  odoo:
    install:
      - docker run -d -p 8080:80 cloud.canister.io:5000/wisedrette/httpd
      - docker run -d -e POSTGRES_USER=odoo -e POSTGRES_PASSWORD=odoo -e POSTGRES_DB=postgres --name db postgres:10
      - docker run -p 80:8069 --name odoo --link db:db -t r.cfcr.io/wisedrette/wisedrette/dockertest:odoo
    subdomain_port_mapping:
      - httpd:8080
    docker_registry:
      - server: r.cfcr.io 
        username: wisedrette
        password: $REGISTRY_PASSWORD
      - server: cloud.canister.io:5000
        username: wisedrette
        password: $REGISTRY_PASSWORD_CANISTER
